uniform mat4 LLY_MMatrix;
uniform mat4 LLY_VMatrix;
uniform mat4 LLY_PMatrix;
uniform mat4 LLY_MVPMatrix;
uniform float LLY_Time;
uniform sampler3D LLY_ColorTable;
uniform bool LLY_UseColorTable;
uniform vec3 LLY_Ambient;
uniform Light LLY_Lights[20];
